[WCAG-15] Fix tabindex on checkout confirm page by removing flex order
spree/spree pull request #10208
Opened 2020-05-29 07:44 UTC by kaliszKrzysztof

2020-05-29 07:58 UTC, AleksandraKaminska approved these changes

2020-06-01 09:56 UTC, damianlegawiec requested changes

2020-06-01 09:56 UTC, damianlegawiec commented on frontend/app/views/spree/checkout/_confirm.html.erb
> +    <%= render partial: 'spree/checkout/delivery_informations', locals: { className: 'd-lg-none' } %>
```suggestion
    <%= render partial: 'spree/checkout/delivery_informations', locals: { class_name: 'd-lg-none' } %>
```

2020-06-01 09:56 UTC, damianlegawiec commented on frontend/app/views/spree/checkout/_confirm.html.erb
> +    <%= render partial: 'spree/checkout/delivery_informations', locals: { className: 'd-lg-none' } %>
we're always using snake case in ruby code :)

2020-06-02 22:04 UTC, damianlegawiec approved these changes

2020-06-02 22:04 UTC, merged