[SD-885] Adds check and flash message when trying to create stock transfer with a variant not available on hand in source location
spree/spree pull request #10365
Opened 2020-07-17 14:35 UTC by aplegatt

2020-08-07 09:16 UTC, przemosk commented on backend/app/controllers/spree/admin/stock_transfers_controller.rb
> +          variant = Spree::Variant.find(variant_id)
```suggestion
          variant = Spree::Variant.unscoped.find(variant_id)
```

2020-08-07 09:17 UTC, przemosk commented on backend/app/controllers/spree/admin/stock_transfers_controller.rb
> +      def any_missing_variants(variant_ids)
if this method return boolean type, name should contain `?`

2020-08-07 09:28 UTC, damianlegawiec requested changes

2020-08-07 09:28 UTC, damianlegawiec commented on backend/app/controllers/spree/admin/stock_transfers_controller.rb
> +      end
```suggestion
      def any_missing_variants?(variant_ids)
        source_location.stock_items.where(variant_id: vartiant_ids, count_on_hand: 0).any?
      end
```

2020-08-12 08:54 UTC, przemosk approved these changes

2020-08-12 23:47 UTC, usman-khan-1 approved these changes

2020-08-20 14:52 UTC, damianlegawiec approved these changes

2020-08-20 15:30 UTC, merged