SD-949 rename r_m_a to its fullname return_merchandise_authorization
spree/spree pull request #10527
Opened 2020-10-06 12:04 UTC by KacperMekarski

The problem was that class RMARequired in classic reload was converted to rma_required to find a matching file, while zeitwerk required file named r_m_a_required. In my opinion best solution is to use fullname of rma (return_merchandise_authorization) which solves the problem of converting class to snake case in both cases.

2020-10-06 13:46 UTC, nnande approved these changes

2020-10-08 19:35 UTC, poudelprakash approved these changes

2020-10-22 22:23 UTC, damianlegawiec reviewed
@KacperMekarski we need to fix this in a way we're not going to change the class name - this will break a lot of current spree instances, decorators and so on

2020-10-23 11:25 UTC, piotrpanko approved these changes

2020-10-29 23:31 UTC, damianlegawiec requested changes
@KacperMekarski 

This can be achieved by creating a `Zeitwerk::Inflector` initializer, eg. https://github.com/solidusio/solidus/blob/466ac8e4b3217dca86bc2194b3dcff56111c3e0c/core/config/initializers/inflections.rb#L3

2020-11-10 10:12 UTC, KacperMekarski commented
@damianlegawiec done.

Works for both classic reload & zeitwerk mode

2020-11-10 10:21 UTC, KacperMekarski commented on core/app/models/spree/return_item/eligibility_validator/default.rb
> -require_relative 'r_m_a_required'
I noticed that `require_relative` does the trick for file named `rma_required` (then adding acronym is not neccessary)

2020-11-10 11:36 UTC, damianlegawiec approved these changes

2020-11-10 14:20 UTC, KacperMekarski commented
@damianlegawiec I rebased from `master`, but tests failed due to error from db migrations:
> Caused by:
NameError: uninitialized constant AddStockLocationToRMA

caused probably by added acronym.
Therefore I used second solution which I mentioned here: https://github.com/spree/spree/pull/10527#discussion_r520449256 which works fine.

2020-11-10 14:26 UTC, closed without merging

2020-11-10 14:32 UTC, KacperMekarski commented
Created new PR: https://github.com/spree/spree/pull/10574