Feature/sd 1370 remove and replace default country id with default country iso
spree/spree pull request #11285
Opened 2021-08-24 12:38 UTC by v10110

https://spark-solutions.atlassian.net/browse/SD-1370

2021-08-24 12:54 UTC, damianlegawiec requested changes

2021-08-24 12:54 UTC, damianlegawiec commented on api/app/serializers/spree/api/v2/platform/store_serializer.rb
> +          has_one :default_country, serializer: :country, record_type: :country, id_method_name: :default_country_iso
@v10110 this shouldn't change, we're not changing the association between Store and Country

2021-08-24 15:03 UTC, damianlegawiec commented on api/app/serializers/spree/v2/storefront/store_serializer.rb
> +                   :twitter, :instagram, :default_locale, :customer_support_email, :default_country_iso, :description,
@v10110 we're not changing Store attribute, only the Spree preference

2021-09-03 08:40 UTC, pmilewski approved these changes

2021-12-02 07:55 UTC, closed without merging