[SD-1447] Checkout unshippable items endpoint
spree/spree pull request #11323
Opened 2021-09-08 13:46 UTC by szymoniwacz

2021-09-09 13:12 UTC, szymoniwacz commented
What's left in this PR is adding API calls documentation.

2021-09-16 15:27 UTC, damianlegawiec requested changes

2021-09-16 15:27 UTC, damianlegawiec commented on core/app/services/spree/checkout/get_unshippable_items.rb
> +      def unshippable_items(order:)
```suggestion
      end

      protected

      def unshippable_items(order:)
```

2021-09-16 15:27 UTC, damianlegawiec commented on core/app/services/spree/checkout/get_unshippable_items.rb
> +        shipping_address_zone_id = Spree::Zone.match(order.shipping_address)&.id
```suggestion
        shipping_address_zone_id = Spree::Zone.match(order.shipping_address)&.id
```

this uses all zones, and not the `order.store.checkout_zone`

2025-06-11 13:27 UTC, closed without merging