Guide: Dev: Update getting started guide
spree/spree pull request #7805
Opened 2017-02-03 05:55 UTC by vfonic

2017-02-03 09:53 UTC, damianlegawiec requested changes

2017-02-03 09:53 UTC, damianlegawiec commented on guides/content/developer/tutorials/getting_started_tutorial.md
> -To run Spree 3.1 you need the latest Rails version, 4.2.6.
@vfonic actually 3.1 requires 4.2.5 https://github.com/spree/spree/blob/3-1-stable/core/spree_core.gemspec#L37

2017-02-03 09:53 UTC, damianlegawiec commented on guides/content/developer/tutorials/getting_started_tutorial.md
> +The latest version of Spree in development is Spree 3.2 RC2. It requires Rails 5
RC2 is really stable and is used on production :) We at Spark use it in all of our new projects

2017-04-15 08:04 UTC, vfonic commented
Seems like this PR is no longer relevant. Closing.

2017-04-15 08:04 UTC, closed without merging