Minor change to workaround globalize bug
spree/spree pull request #7831
Opened 2017-03-04 14:37 UTC by k3rn31

This is the only way I found to workaround a bug introduced by
globalize/globalize on spree_contrib/spree_globalize. See pull request
'#6677' for more.

2017-03-08 16:29 UTC, mauazua requested changes

2017-03-08 16:29 UTC, mauazua commented on backend/app/controllers/spree/admin/resource_controller.rb
> +        send("find_by", parent_data[:find_by].to_s => params["#{resource.model_name}_id"])
hi, @k3rn31 in your comment you specify that `find_by` should not be used but in the line below you use it anyway. Are you sure that this is ok? Besides that, could you please pass the first argument to `send` as a symbol?

2017-03-08 16:32 UTC, mauazua commented
hi, @k3rn31. Thanks for submitting this pull request. Could you please tell me, in what case did you encounter this issue again?

2017-03-09 08:12 UTC, k3rn31 commented
Hi Marta, thanks for considering my PR.
The issue is due to the "globalize/globalize" gem which is included in "spree_contrib/globalize". The bug (globalize/globalize #423) breaks 'find_by_attribute_name' (sorry I miss-typed the comment, I will fix it in the next commit) raising a "NoMethodError in Spree::Admin::ProductPropertiesController#index" when you open  "/admin/products/example-product/product_properties".
You can take a look at the merged PR #6677 fixing the same problem in another part of spree.
I hope this explains it all.

2017-03-09 08:13 UTC, k3rn31 commented on backend/app/controllers/spree/admin/resource_controller.rb
> +        send("find_by", parent_data[:find_by].to_s => params["#{resource.model_name}_id"])
Hi i fixed the comment and passed the first argument to send as symbol as requested. Let me know if it is ok now. Thanks.

2017-03-09 09:42 UTC, mauazua commented
hi, @k3rn31, thanks for the explanation. I think it's all ok now, but please squash your commits into one :)

2017-03-09 12:08 UTC, k3rn31 commented
Ok Marta, the commits are squashed together.

2017-03-09 13:47 UTC, mauazua approved these changes

2017-03-10 08:37 UTC, merged