Add Error Flash messages to Taxon Upadate controller action
spree/spree pull request #7947
Opened 2017-04-20 10:27 UTC by charliestarkpl

2017-04-20 10:34 UTC, krzysiek1507 requested changes

2017-04-20 10:34 UTC, krzysiek1507 commented on backend/app/controllers/spree/admin/taxons_controller.rb
> +          flash[:error] = @taxon.errors.full_messages.to_sentence
@charliestarkpl please handle json format and please add specs for it!

2017-04-21 11:11 UTC, nnande requested changes

2017-04-21 11:11 UTC, nnande commented on backend/app/views/spree/admin/taxons/_form.html.erb
> +        <%= f.error_message_on :name, class: 'error-message', value: @taxon.name %>
@charliestarkpl There is no need to explicitly set ```:value``` attr, the ```FormBuilder``` object will handle that for you. https://apidock.com/rails/ActionView/Helpers/FormHelper/form_for

> For fields generated in this way using the FormBuilder, if :person also happens to be the name of an instance variable @person, the default value of the field shown when the form is initially displayed (e.g. in the situation where you are editing an existing record) will be the value of the corresponding attribute of @person.

It concerns all the changes introduced in this file. In my opinion you could drop this commit :-)

2017-04-21 12:04 UTC, nnande approved these changes

2017-04-24 10:33 UTC, mauazua commented on backend/app/controllers/spree/admin/taxons_controller.rb
> +          @update_children = true if params[:taxon][:name] != @taxon.name || params[:taxon][:permalink] != @taxon.permalink
@charliestarkpl I believe you don't have to implicitly set `true` here depending on this `if-condition` result. This expression will returns a boolean value, so you can make advantage of it, and simply write:
`@update_children = (params[:taxon][:name] != @taxon.name || params[:taxon][:permalink] != @taxon.permalink)`
and you will also get rid of the hound warning :)

2017-04-24 15:11 UTC, merged