Avoid postgres distict order by issue with in_taxons
spree/spree pull request #7950
Opened 2017-04-21 11:42 UTC by vishalzambre

## Description

If we use `in_taxons` method on taxon show page in postgres it throws error because at taxon page it also uses `in_taxon` scope and in this scope `order("spree_products_taxons.position ASC")` is used.

2017-04-24 22:05 UTC, damianlegawiec requested changes

2017-04-24 22:05 UTC, damianlegawiec commented on core/app/models/spree/product/scopes.rb
> +        joins(:classifications).where(spree_products_taxons: { taxon_id: ids })
@vishalzambre please use `Spree::Classification.table_name` here, thanks!

2017-04-25 05:24 UTC, zambrevishal commented
@damianlegawiec Updated changes.

2017-04-25 05:26 UTC, vishalzambre commented
@damianlegawiec Updated changes.

2017-04-26 10:34 UTC, nnande commented
merged via #7967

2017-04-26 10:34 UTC, closed without merging