[Admin-End] fix shipment tax issue when a tax category is present on shipment method
spree/spree pull request #7997
Opened 2017-05-13 15:51 UTC by nimish13

**Issue**
When a tax category is present on shipment method and order is placed from admin end, then the shipment tax is calculated after the order gets completed.
This makes order's ``payment_state`` to ``balance_due``  even after capturing the payment.

**Steps to Replicate**
1. Add a tax category to any shipment method.
2. Create a new order from Admin End.
3. Now make the payment and complete the order.
4. Now capture the payment, you will still see order's payment state as ``balance_due``.

For ex. lets say
Order Total - $30
Shipment Total - $5
Tax Rate on shipment is 10%
So shipment tax would be $0.5
Now, this shipment tax is added to order's total only when the order gets completed and modify the Order Total to $30.5.
But the payment that was captured was of only $30.

**Reason**
When we move to payment tab from admin end, Order's state is still ``delivery`` and in Spree, tax amount on shipment is calculated when order moves to ``payment`` state.

2017-05-15 10:20 UTC, tanmay3011 commented on backend/app/controllers/spree/admin/payments_controller.rb
> +        @order.next if @order.delivery?
@nimish13 What delivery state is skipped in the checkout_flow of order. This would raise an exception?

2017-05-20 18:42 UTC, damianlegawiec requested changes

2017-05-20 18:42 UTC, damianlegawiec commented on backend/app/controllers/spree/admin/payments_controller.rb
> +        @order.next if @order.delivery?
@nimish13 there should be a check if order has the delivery step

2017-05-27 10:07 UTC, nimish13 commented
@damianlegawiec Thanks for suggesting the changes. I had made the changes. Please review :)

2017-06-03 12:46 UTC, nimish13 commented
@damianlegawiec Any updates on this? :)

2017-06-10 12:59 UTC, nimish13 commented
@damianlegawiec Any updates on this? :)

2017-06-12 08:26 UTC, merged