Loosen our dependency on FriendlyId
spree/spree pull request #8072
Opened 2017-06-17 17:24 UTC by damianlegawiec

FriendlyId should be used only for SEO purposes (product URLs, taxon permalinks) not for models like Order/Shipment/Payment which uses NumberGenerator. Switching back to standard rails finders. 

Basically, reverts https://github.com/spree/spree/commit/259c6b3aeec894f93f19d0220011c23496889f14

2017-06-17 19:14 UTC, krzysiek1507 requested changes
I'm worried about `friendly.find(params[:id])` => `find_by!(number: params[:id])` change. It's breaking change in some cases

2017-06-17 19:14 UTC, krzysiek1507 commented on core/app/models/spree/order.rb
> +      number.to_s
It returns an empty string for nil. It should be `nil`
```ruby
number.presence.to_param
```

2017-06-17 19:14 UTC, krzysiek1507 commented on core/app/models/spree/order.rb
> +      number.to_s
Should we move it to mixin or sth?

2017-06-17 19:14 UTC, krzysiek1507 commented on api/app/controllers/spree/api/v1/payments_controller.rb
> +            @order = Spree::Order.find_by(number: order_id)
`find_by!` (missing bang)

2017-06-17 19:14 UTC, krzysiek1507 commented on api/app/controllers/spree/api/v1/orders_controller.rb
> +            @order = Spree::Order.lock(lock).find_by!(number: params[:id])
I hope it was only `number` using here

2017-06-18 13:41 UTC, damianlegawiec commented on core/app/models/spree/order.rb
> +      number.to_s
@krzysiek1507 It will never return nil or empty string, you cannot create a record with empty number field

2017-06-18 13:42 UTC, damianlegawiec commented on api/app/controllers/spree/api/v1/orders_controller.rb
> +            @order = Spree::Order.lock(lock).find_by!(number: params[:id])
@krzysiek1507 all API calls are number based, that's what official guides enforced years ago

2017-06-18 14:01 UTC, damianlegawiec commented on api/app/controllers/spree/api/v1/payments_controller.rb
> +            @order = Spree::Order.find_by(number: order_id)
@krzysiek1507 fixed

2017-06-18 14:11 UTC, krzysiek1507 requested changes

2017-06-18 14:11 UTC, krzysiek1507 commented on core/app/models/spree/order.rb
> +      number.to_s
@damianlegawiec but we should use [`to_param`](http://guides.rubyonrails.org/active_support_core_extensions.html#to-param) and leave it in particular models
https://github.com/norman/friendly_id/blob/aff0564584e84ffa505e6e278b65ca3c4ee5d698/lib/friendly_id/base.rb#L259-L270

2017-06-18 21:47 UTC, damianlegawiec commented on core/app/models/spree/order.rb
> +      number.to_s
@krzysiek1507 done

2017-06-19 15:10 UTC, merged