respond with correct user list if params has ids query
spree/spree pull request #8142
Opened 2017-07-14 20:08 UTC by kitwalker12

On the Promotion User Rule view. The `initSelection` call in `user_picker.js` calls the Users api with `ids` as the query param, but the action does not look at that query params so we get a random list of users for that page. 

Adding conditional block to run a different query if ids query detected. (Similar code was in other API controllers)

2017-07-14 23:47 UTC, krzysiek1507 requested changes

2017-07-14 23:47 UTC, krzysiek1507 commented on api/app/controllers/spree/api/v1/users_controller.rb
> +          end
Can we clean it a little? Maybe something like below?
```ruby
@users = Spree.user_class.accessible_by(current_ability, :read)

@users = if params[:ids]
           @users.ransack(id_in: params[:ids].split(','))
         else
           @users.ransack(params[:q])
         end

@users.result.page(params[:page]).per(params[:per_page])
```

2017-07-15 00:46 UTC, kitwalker12 commented
Updated @krzysiek1507

2017-07-15 08:23 UTC, krzysiek1507 approved these changes

2017-07-15 15:20 UTC, merged