always record canceled_at when cancel an order
spree/spree pull request #8197
Opened 2017-08-02 10:43 UTC by wuboy0307

If I create a system job to cancelled unpay orders. cancelled_at won't set.

2017-09-07 12:36 UTC, damianlegawiec commented
We shouldn't mix business logic like this with sending out emails. It's not a good future-proof design.

2017-09-08 03:20 UTC, wuboy0307 commented
However, a canceled_at column should record timestamp when this order canceled, no matter how we do it. It doesn't matter cancel by admin, cancel by user, or cancel by cron job. Just need to record the time. It's weird when order state is canceled but canceled_at is still null. Just like order state is complete then complete_at should be set.

2017-09-08 11:59 UTC, damianlegawiec commented
@wuboy0307 sorry - my mistake, can you fix the conflict in code?

2018-02-07 13:53 UTC, bbonislawski requested changes

2018-02-07 13:53 UTC, bbonislawski commented on core/app/models/spree/order.rb
> +      send_cancel_email
Please remove this trailing whitespace so I can merge it

2018-02-07 13:53 UTC, bbonislawski commented
There is failing test caused by your changes too. Please update it

2018-06-26 05:45 UTC, keonjeo commented on core/app/models/spree/order.rb
> +          canceler_id: user.id
```ruby
update_columns(canceler_id: user.id)
```
keep them in one line. thx.

2018-06-26 05:46 UTC, keonjeo commented on core/app/models/spree/order.rb
> +      )
keep them in the same line for clean code style. thx.

2026-01-16 09:05 UTC, closed without merging