adds try in order listing for handling destroyed approver
spree/spree pull request #8390
Opened 2017-10-09 12:24 UTC by yatindrarao

2017-10-09 14:12 UTC, damianlegawiec requested changes

2017-10-09 14:12 UTC, damianlegawiec commented on backend/app/views/spree/admin/shared/_order_summary.html.erb
> +          <td><%= @order.approver ? @order.approver.email : "" %></td>
@	yatindrarao you can use `@order.approver.try(:email)`

2017-10-10 16:30 UTC, damianlegawiec approved these changes

2017-10-12 12:13 UTC, bbonislawski commented
Hello @yatindrarao, 
I've cherry-picked your commit and created separate pull request in #8397 so we have correct history of commits(without old commits that shouldn't be in repo) with your name included in it so you'll be included in contributors of Spree.

I really appreciate your help, thanks! We'll merge it as soon as CI build successes.

2017-10-12 12:13 UTC, closed without merging

2017-10-12 13:23 UTC, yatindrarao commented
Thanks @bbonislawski   :+1: