rename icon to spree_icon and breadcrumbs to spree_breadcrumbs
spree/spree pull request #8445
Opened 2017-11-02 12:43 UTC by bbonislawski

2017-11-02 15:14 UTC, krtschmr commented
very useful! should be merged.

2017-11-03 12:11 UTC, damianlegawiec requested changes
@bbonislawski please add note about it in the https://github.com/spree/spree/blob/master/guides/content/release_notes/3_5_0.md

2017-11-03 12:11 UTC, damianlegawiec commented on backend/app/helpers/spree/admin/navigation_helper.rb
> +      alias :icon :spree_icon
@bbonislawski we need deprecation warnings for usage of the old methods so other developers will know about this change and that they need to reflect it in their custom frontends if they do use it

2017-11-07 07:07 UTC, damianlegawiec approved these changes

2017-11-07 09:26 UTC, merged