Fixes #8502
spree/spree pull request #8591
Opened 2018-02-09 10:55 UTC by saravanak

This commit fixes the searching of the taxons when the request searching
within a `taxonomy`.

The code is re-arranged a bit to DRY the ransack call.

There is a `skipped` test which is the case of searching for nested
taxons. I am leaving that open for discussion in this PR.

2018-02-09 11:24 UTC, bbonislawski commented
Thank you for your contribution but 19 specs failed and codeclimate reported 4 issues. Please fix these things

2018-02-09 12:37 UTC, saravanak commented
Sure @bbonislawski . I need some help here: there are 3 containers that are successful runs, while one container fails. 
Can you help me here? I see that the same `build-ci.rb` file has successfully executed in the other 3 containers

2018-02-09 13:44 UTC, bbonislawski commented
What kind of help do you need? All specs in `spec/controllers/spree/api/v1/taxons_controller_spec.rb` failed because of your changes.

2018-02-09 17:31 UTC, saravanak commented
@bbonislawski I have fixed the commits, just one spacing issue (will run rubocop in local henceforth).. Shoul I squash these commits along with the codeclimate correction?

2018-02-09 18:03 UTC, bbonislawski requested changes

2018-02-09 18:03 UTC, bbonislawski commented on api/spec/controllers/spree/api/v1/taxons_controller_spec.rb
> +          context 'searching for top level taxon' do
You don't test if it searched correctly. This test would pass even if api returned `rust_taxon` as second element in array.

2018-02-09 18:04 UTC, bbonislawski commented
@saravanak yes, please fix issue with codeclimate, add spec to check if only one item was returned and squash commits. Thanks!

2018-02-12 07:51 UTC, closed without merging

2018-02-12 08:09 UTC, saravanak commented
I have pushed with the above changes @bbonislawski: 

1. rubocop warning
2. Your comment about the additional case for testing
3. Squashed the commits

 I deleted and recreated the branch, and this lead to the close of the PR. I am not able to reopen this PR now. Please let me know if have to follow a different procedure for squashing. 

Apologies for the trouble if any and thanks for the comments!