Redirect to edit user after creation
spree/spree pull request #8603
Opened 2018-02-13 18:42 UTC by mohsen-alizadeh

#8589

2018-02-13 19:38 UTC, bbonislawski commented
Thanks for your contribution @mohsen-alizadeh but lots of spec failed, can you try to fix them or find the reason why they fail? https://circleci.com/gh/spree/spree/6706#tests/containers/1

2018-02-13 19:51 UTC, artplan1 commented
@bbonislawski 
same errors exists in master branch, latest merge commit build failed:
https://circleci.com/gh/spree/spree/6699#tests/containers/1

2018-02-13 19:52 UTC, bbonislawski commented
Thanks @artplan1 for noticing. I didn't 😱 Going to fix them asap

2018-02-13 19:54 UTC, mohsen-alizadeh commented
@bbonislawski please merge this PR, I'm going to investigating on errors exist on master and I will create another PR for that

2018-02-13 19:55 UTC, artplan1 commented
also @mohsen-alizadeh can you fix this issue for `user update` too? it should redirect

2018-02-13 20:10 UTC, mohsen-alizadeh commented
@artplan1 Done

2018-02-13 20:29 UTC, artplan1 commented
@mohsen-alizadeh 
thank you.

Did you check it in admin panel locally? I think because of this way (redirect) `flash.now` methods will not work and user will not see any notifications. It should be just `flash` if it's before redirect.

in case of `update` I'm not sure that user will see validation errors on save (if something is wrong)  because of redirect instead of render.

it can be tested in feature specs too

2018-02-13 20:34 UTC, bbonislawski commented
Sorry for the problems with specs. I've fixed it in #8604 . Please rebase against current master and push again

2018-02-14 06:17 UTC, mohsen-alizadeh commented
@bbonislawski It's ready to merge

2018-02-14 07:32 UTC, artplan1 requested changes

2018-02-14 07:32 UTC, artplan1 commented on backend/app/controllers/spree/admin/users_controller.rb
>            flash.now[:success] = flash_message_for(@user, :successfully_created)
`flash.now` will not work here

2018-02-14 08:52 UTC, bbonislawski commented
@mohsen-alizadeh please squash the commits and I'll merge it. Thanks 👍

2018-02-14 09:39 UTC, artplan1 commented
Great job @mohsen-alizadeh 
Thank you

2018-02-14 09:39 UTC, bbonislawski commented
![tenor-2](https://user-images.githubusercontent.com/7106611/36197142-4b3cb7d4-1173-11e8-9604-49b318ca95c6.gif)

2018-02-14 09:41 UTC, bbonislawski commented
Thanks @mohsen-alizadeh , you're awesome!

2018-02-14 09:41 UTC, merged