Add preview product button on products edit page
spree/spree pull request #8636
Opened 2018-03-13 14:50 UTC by dimon-k

2018-03-13 14:55 UTC, damianlegawiec requested changes

2018-03-13 14:55 UTC, damianlegawiec commented on core/app/helpers/spree/products_helper.rb
> +    def frontend_available?
@dimon-k let's move it to `BaseHelper`

2018-03-13 14:55 UTC, damianlegawiec commented on backend/app/views/spree/admin/products/edit.html.erb
> +  <% if frontend_available? %>
👍

2018-03-14 14:53 UTC, bbonislawski requested changes

2018-03-14 14:53 UTC, bbonislawski commented on backend/spec/features/admin/products/edit/products_spec.rb
> +      page.find('#admin_preview_product')
`expect(page).to have_css('#admin_preview_product')` please

2018-03-14 14:53 UTC, damianlegawiec requested changes

2018-03-14 14:53 UTC, damianlegawiec commented on backend/spec/features/admin/products/edit/products_spec.rb
> +    it 'has a link to preview product' do
`has a link to preview product` -> `has a link to preview a product`

2018-03-14 14:53 UTC, damianlegawiec commented on backend/spec/features/admin/products/edit/products_spec.rb
> +      allow_any_instance_of(Spree::BaseHelper).to receive(:product_url).and_return('#')
`and_return('#')` -> `and_return('http://example.com/products/product-slug')`

2018-03-14 15:22 UTC, damianlegawiec requested changes

2018-03-14 15:22 UTC, damianlegawiec commented on backend/spec/features/admin/products/edit/products_spec.rb
> +      expect(page).to have_css('#admin_preview_product')
@dimon-k sorry forgot, let's add a 

```
expect(page).to have_content('http://example.com/products/product-slug')
```

2018-03-14 15:28 UTC, dimon-k commented on backend/spec/features/admin/products/edit/products_spec.rb
> +      expect(page).to have_css('#admin_preview_product')
good point @damianlegawiec

2018-03-14 16:52 UTC, damianlegawiec reviewed
👍

2018-03-14 17:06 UTC, damianlegawiec approved these changes

2018-03-15 09:38 UTC, closed without merging