Created promotion seed
spree/spree pull request #8726
Opened 2018-05-08 15:20 UTC by WitekL

2018-05-08 15:43 UTC, damianlegawiec approved these changes

2018-05-09 11:40 UTC, bbonislawski requested changes

2018-05-09 11:40 UTC, bbonislawski commented on core/db/default/spree/promotions.rb
> +  preferences: { match_policy: 'any', eligible_values: { '6' => '5,1' } }
Hardcoded ID

2018-05-14 08:04 UTC, bbonislawski approved these changes

2018-05-14 08:04 UTC, merged

2018-07-01 08:38 UTC, safeforge commented
@WitekL after this merge seems to be not possible to install spree (3.6.1) with seeds and without samples on rails (5.2.0)

```
$ rails g spree:install --migrate=true --sample=false --seed=true --copy_views=false

...
loading ruby ../spree_core-3.6.1/db/default/spree/countries.rb
loading ruby ../spree_core-3.6.1/db/default/spree/default_reimbursement_type.rb
loading ruby ../spree_core-3.6.1/db/default/spree/promotions.rb
Loaded Option Types samples
Loaded Option Values samples
Loaded Tax Categories samples
Loaded Shipping Categories samples
Loaded Products samples
loading ruby ../spree_core-3.6.1/db/default/spree/roles.rb
loading ruby ../spree_core-3.6.1/db/default/spree/states.rb
loading ruby ../spree_core-3.6.1/db/default/spree/stores.rb
loading ruby ../spree_core-3.6.1/db/default/spree/zones.rb
loading ruby ../spree_auth_devise-3.3.3/db/default/users.rb
...
```

my expectations was to have a database with seeds without products, but in the console:

```
irb(main):002:0> Spree::Product.count
   (1.0ms)  SELECT COUNT(*) FROM "spree_products" WHERE "spree_products"."deleted_at" IS NULL
=> 16
```

spree should works without `promotions` and I was wondering if it's a good idea to move `core/db/default/spree/promotions.rb` in `sample/db/sample/promotions.rb`

/cc @bbonislawski @damianlegawiec

2018-07-02 08:51 UTC, WitekL commented
@safeforge Thanks for reporting this issue. I will attend it right away