(WIP) API V2 cart_controller docs
spree/spree pull request #8865
Opened 2018-06-26 14:33 UTC by WitekL

2018-06-27 10:25 UTC, bbonislawski requested changes

2018-06-28 09:25 UTC, bbonislawski approved these changes

2018-06-28 12:55 UTC, WitekL commented
@damianlegawiec can you take a look at this? 🙂

2018-06-28 21:28 UTC, damianlegawiec commented
@WitekL can we merge https://github.com/spree/spree/pull/8868 before and rebase this one? It will reduce are swagger code-bloat :)

2018-06-29 11:09 UTC, WitekL commented
@damianlegawiec It's probably good to go :)

2018-07-02 09:19 UTC, damianlegawiec approved these changes

2018-07-02 09:19 UTC, merged