Add Product List to API V2 docs (WIP)
spree/spree pull request #8887
Opened 2018-07-09 11:03 UTC by damianlegawiec

2018-07-10 11:30 UTC, VygovskySergey commented
Should we add to filtering, query by ids?

2018-07-10 12:05 UTC, damianlegawiec commented
@VygovskySergey good idea - by IDs you mean product IDs, correct?

2018-07-10 12:13 UTC, VygovskySergey commented
@damianlegawiec Yeah, that what I mean

2018-07-17 09:55 UTC, kushniryb commented
@damianlegawiec 
This update introduces the following errors - https://d.pr/free/i/0MqTmF

2018-07-17 09:56 UTC, kushniryb requested changes
@damianlegawiec 
This update introduces following errors - https://d.pr/free/i/0MqTmF

2018-08-15 10:47 UTC, damianlegawiec commented
@kushniryb fixed!

2018-08-16 07:34 UTC, VygovskySergey commented on api/docs/v2/storefront/index.yaml
> +              <li>price (ascending/descenging)</li>
duplication

2018-08-16 07:34 UTC, VygovskySergey commented on api/docs/v2/storefront/index.yaml
> +        /api/v1/products/1 </code> <br /><br />Note that the API will attempt a
`/api/v2/products/1`

2018-08-16 09:38 UTC, VygovskySergey approved these changes
LGTM

2018-08-16 09:40 UTC, kushniryb approved these changes
👍

2018-08-16 09:41 UTC, merged