Make currency public in Spree::ReturnItem
spree/spree pull request #9005
Opened 2018-09-24 14:09 UTC by btolarz

It fixes currency display for ReturnItem in Admin::ReturnAuthorizationsController

2018-09-24 14:55 UTC, VygovskySergey requested changes

2018-09-24 14:55 UTC, VygovskySergey commented on core/spec/models/spree/return_item_spec.rb
> +        excpect { subect.respond_to?(:currency) }.to eq true
`subject`

2018-09-24 15:06 UTC, VygovskySergey requested changes

2018-09-24 15:06 UTC, VygovskySergey commented on core/spec/models/spree/return_item_spec.rb
> +        excpect { subject.respond_to?(:currency) }.to eq true
`expect` :)

2018-09-26 11:36 UTC, damianlegawiec approved these changes

2018-09-26 11:43 UTC, VygovskySergey approved these changes

2018-09-26 14:00 UTC, merged