User API v2 Add to Cart API endpoint instead of OrdersController#populate
spree/spree pull request #9050
Opened 2018-10-22 13:33 UTC by damianlegawiec

2018-10-23 11:05 UTC, oleksify requested changes

2018-10-23 11:05 UTC, devilcoders commented on frontend/app/assets/javascripts/spree/frontend/product.js
> +Spree.ready(function ($) {
No jQuery 🎉 is used in this function, so no need for `$`
```suggestion
Spree.ready(() => {
```

2018-10-23 11:05 UTC, devilcoders commented on frontend/app/assets/javascripts/spree/frontend/product.js
> +              // redirect wity `variant_id` is crucial for analytics tracking
Typo
```suggestion
              // redirect with `variant_id` is crucial for analytics tracking
```

2018-10-23 11:05 UTC, devilcoders commented on frontend/app/assets/javascripts/spree/frontend/product.js
> +              window.location = Spree.routes.cart + '?variant_id=' + variantId.toString()
```suggestion
              window.location = `${Spree.routes.cart}?variant_id=${variantId.toString()}`
```

2018-10-23 11:07 UTC, damianlegawiec commented on api/app/assets/javascripts/spree/api/storefront/cart.js
> +  var createCartUrl = Spree.routes.api_v2_storefront_cart_create
@devilcoders this is still built with asset pipeline so no ES6 support :(

2018-10-26 15:24 UTC, pl-spark requested changes

2018-10-27 07:33 UTC, damianlegawiec commented on api/app/controllers/spree/api/v2/storefront/cart_controller.rb
> +          include ActionController::Cookies
@piotrleniec-spark it's required for the default rails frontend , we don't read cookies anywhere in API v2, authorization is based on API tokens

2018-10-28 10:50 UTC, damianlegawiec commented on api/app/controllers/spree/api/v2/storefront/cart_controller.rb
> +          include ActionController::Cookies
@piotrleniec-spark fixed via https://github.com/spree/spree/pull/9050/commits/5fbc8d48742ebd08a1792c6c14725e07511fea0a

2018-10-29 08:44 UTC, piotrleniec-spark commented on frontend/app/assets/javascripts/spree/frontend/cart.js
> +            SpreeAPI.orderToken = json.token
@damianlegawiec, maybe we could also store that token in `localStorage`?

2018-10-29 08:52 UTC, pl-spark approved these changes

2018-10-29 09:01 UTC, oleksify approved these changes

2018-10-29 12:05 UTC, merged