Add .cache in general_settings/edit.html.erb
spree/spree pull request #9419
Opened 2019-06-11 10:30 UTC by jumbosushi

### What

Add `.cache` class to clear cache card div in `general_settings/edit.html.erb`

### Why

Lately I wanted to create a deface override to clear cache card in `general_settings/edit.html.erb`, but noticed that didn't have a unique class to be used as css selector. I ended up using hacky css selector rule, but this would make it much easier.

2019-06-14 17:28 UTC, MatthewKennedy commented
Personally in this scenario I would use id="cache" or id="cache-settings", each id is intended to be unique to one element in the dom, ideal for targeting something like this, also using an id rather than adding another class clearly separates the bootstrap styling from the id for potential deface override targeting.

2019-06-15 19:42 UTC, damianlegawiec requested changes

2019-06-15 19:42 UTC, damianlegawiec commented on backend/app/views/spree/admin/general_settings/edit.html.erb
> +          <div class="card mb-3 cache">
```suggestion
          <div class="card mb-3" id="general-settings-cache" data-hook="general_settings_cache">
```

2019-06-16 00:28 UTC, jumbosushi commented
Thanks for the suggestion! Would it be a good idea to make an another PR to add `id` to currency card div as well?

2019-06-16 08:44 UTC, damianlegawiec commented
That would be awesome @jumbosushi - thanks!

2019-06-16 08:45 UTC, damianlegawiec approved these changes

2019-06-16 08:45 UTC, merged