Adds available method to product model and corrects products sort
spree/spree pull request #9637
Opened 2019-11-20 13:05 UTC by PSzyszkaSpark

Fixes https://github.com/spree/spree/issues/9634

2019-11-20 13:49 UTC, damianlegawiec requested changes

2019-11-20 13:49 UTC, damianlegawiec commented on core/app/models/spree/product.rb
> +  def self.available
@PSzyszkaSpark there's already an `available` scope defined here

https://github.com/spree/spree/blob/1da20381892509df9a472f450300daf32241b89d/core/app/models/concerns/spree/product_scopes.rb#L202

2019-11-21 10:04 UTC, haukurhrafn commented
I wonder wether it's a good idea to have  show_available as a filter. Since this is the storefront api any user can change that value and view products that have not been made available. Seems a bit “leaky” to me.

In a scenario where a store is launching an exclusive product on a future date important details might be leaked out before the set available date.

In my opinion admins are the only users that should have access to products that have not been made available. Same goes for discontinued.

2019-11-21 10:51 UTC, damianlegawiec requested changes

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +        @available        = params.dig(:filter, :show_available)
```suggestion
        @not_available        = params.dig(:filter, :show_not_available)
```

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +        products = include_available(products)
```suggestion
        products = include_not_available(products)
```

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +      def include_available(products)
```suggestion
      def include_not_available(products)
```

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +        if available
```suggestion
        if not_available
```

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/models/concerns/spree/product_scopes.rb
> +      def self.available(available_on = nil, only_not_discontinued = true, _currency = nil)
@PSzyszkaSpark please don't change the logic of this method

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +        end
```ruby
else
  products.available
end
```

will do fine, we don't need additional logic around discontinued

2019-11-21 10:51 UTC, damianlegawiec commented on core/app/finders/spree/products/find.rb
> +        products = include_available(products)
@PSzyszkaSpark we need to change the order of scopes here

```ruby
products = include_available(products)
products = include_discontinued(products)
products = include_deleted(products)
```

2019-11-21 12:52 UTC, damianlegawiec commented
@haukurhrafn we don't want to change this functionality now, only fix that by default endpoints should return only available products. However, you can alter this in your project codebase - https://guides.spreecommerce.org/developer/customization/logic.html

2019-11-21 12:52 UTC, damianlegawiec approved these changes

2019-11-21 12:53 UTC, merged