Move translations from spree design
spree/spree pull request #9648
Opened 2019-11-25 13:36 UTC by pmilewski

2019-11-25 13:40 UTC, damianlegawiec requested changes

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> -    product: Product
@pmilewski let's keep `product` key in tact

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> +    product:
```suggestion
    pdp:
```

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> -    checkout: Checkout
@pmilewski let's leave `checkout` in-tact

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> +    checkout:
```suggestion
    checkout_page:
```

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> -    cart: Cart
@pmilewski let's leave `cart` in-tact

2019-11-25 13:40 UTC, damianlegawiec commented on core/config/locales/en.yml
> +    cart:
```suggestion
    cart_page:
```

2019-11-25 13:43 UTC, przemosk commented on core/config/locales/en.yml
> +      empty_info: "Your cart is empty.<br />There are no items in your cart."
```suggestion
      empty_info: 'Your cart is empty.<br />There are no items in your cart.'
```

2019-11-26 10:48 UTC, damianlegawiec approved these changes

2019-11-26 10:49 UTC, merged