[SD-260] arrows possitions on homepage carousels
spree/spree pull request #9729
Opened 2019-12-31 09:25 UTC by pmilewski

2019-12-31 09:28 UTC, pl-spark requested changes

2019-12-31 09:28 UTC, piotrleniec-spark commented on frontend/app/assets/stylesheets/spree/frontend/components-bootstrap/carousel.scss
> +        height: 81% !important;
Is `!important` necessary?

2019-12-31 09:28 UTC, piotrleniec-spark commented on frontend/app/assets/stylesheets/spree/frontend/components-bootstrap/carousel.scss
> +        height: 81% !important;
Are we sure that height set to 81% is responsive across all devices?

2019-12-31 09:32 UTC, AleksandraKaminska submitted a review, later dismissed
<img width="1323" alt="Zrzut ekranu 2019-12-31 o 10 31 25" src="https://user-images.githubusercontent.com/26117538/71616887-c6f2d000-2bb8-11ea-87ea-b425575278f9.png">
I think it shouldn't look like this

2019-12-31 13:04 UTC, pl-spark requested changes

2019-12-31 13:04 UTC, piotrleniec-spark commented on frontend/app/views/spree/home/_carousel.html.erb
> +                <% if item == sliced_items.first %>
It'd be cleaner to use `each_with_index` and compare indices instead of using object equality.

2020-01-02 08:31 UTC, pl-spark approved these changes

2020-01-02 09:12 UTC, merged