[SD-663] Add missing values for PDP Structured Data
spree/spree pull request #9757
Opened 2020-01-08 11:36 UTC by pmilewski

2020-01-08 15:55 UTC, damianlegawiec requested changes

2020-01-08 15:55 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
>          crumbs << taxon.ancestors.where.not(parent_id: nil).map { |ancestor| content_tag(:li, content_tag(:span, link_to(content_tag(:span, ancestor.name, itemprop: 'name'), seo_url(ancestor, params:
`itemid` and `position` needed here as well

2020-01-08 15:55 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        crumbs << content_tag(:li, content_tag(:span, link_to(content_tag(:span, taxon.name, itemprop: 'name'), seo_url(taxon, params: permitted_product_params), itemprop: 'url') + separator, itempro
@pmilewski this cannot be `position: 1`, the line above you've got an iteration of taxon ancestors, so this should be a  subsequent number based on the number of ancestors eg `position: taxon.ancestors.count + 1`

2020-01-09 11:06 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        crumbs << content_tag(:li, content_tag(:span, link_to(content_tag(:span, taxon.name, itemprop: 'name'), seo_url(taxon, params: permitted_product_params), itemprop: 'url') + separator, itempro
```suggestion
        crumbs << content_tag(:li, content_tag(:span, link_to(content_tag(:span, taxon.name, itemprop: 'name'), seo_url(taxon, params: permitted_product_params), itemprop: 'url') + separator, itemprop: 'item'), class: 'breadcrumb-item', itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListElement', itemid: seo_url(taxon, params: permitted_product_params), position: taxon.ancestors.where.not(parent_id: nil).count + 1)
```

2020-01-09 11:06 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        crumbs << taxon.ancestors.where.not(parent_id: nil).map.with_index { |ancestor, index| content_tag(:li, content_tag(:span, link_to(content_tag(:span, ancestor.name, itemprop: 'name'), seo_url
```suggestion
        crumbs << taxon.ancestors.where.not(parent_id: nil).map.with_index { |ancestor, index| content_tag(:li, content_tag(:span, link_to(content_tag(:span, ancestor.name, itemprop: 'name'), seo_url(ancestor, params: permitted_product_params), itemprop: 'url') + separator, itemprop: 'item'), itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListElement', itemid: seo_url(ancestor, params: permitted_product_params), class: 'breadcrumb-item', position: index + 1) } if taxon.ancestors.any?
```

2020-01-09 11:06 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
>          crumbs << content_tag(:li, content_tag(:span, content_tag(:span, product.name) + separator), class: 'breadcrumb-item') if product
@pmilewski shouldn't we add position here as well plus itemid?

2020-02-06 11:39 UTC, pmilewski commented
https://github.com/spree/spree/pull/9815/files

2020-02-06 11:39 UTC, closed without merging