[SD-680] Implement $font-family variable
spree/spree pull request #9775
Opened 2020-01-10 11:36 UTC by pmilewski

2020-01-10 14:18 UTC, damianlegawiec requested changes
We don't need the

This needs to be changed in more places also:

1. https://github.com/spree/spree/blob/babfd2deed7c5adc474e3068380d0138f6febe20/frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/category_nav_bar.scss#L79
2. https://github.com/spree/spree/blob/b0814469b0df3603b8567edb20de1e686c3e5855/frontend/app/assets/stylesheets/spree/frontend/variables/bootstrap-overrides.scss#L23

2020-01-10 14:18 UTC, damianlegawiec commented on frontend/app/assets/stylesheets/spree/frontend/views/spree/layouts/spree_application.scss
> +body {
We don't need this, we need to change this here:

1. https://github.com/spree/spree/blob/babfd2deed7c5adc474e3068380d0138f6febe20/frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/category_nav_bar.scss#L79
2. https://github.com/spree/spree/blob/b0814469b0df3603b8567edb20de1e686c3e5855/frontend/app/assets/stylesheets/spree/frontend/variables/bootstrap-overrides.scss#L23

2020-01-10 15:16 UTC, damianlegawiec commented on frontend/app/assets/stylesheets/spree/frontend/variables/variables.scss
> +$font-family: Montserrat, sans-serif;
```suggestion
$font-family: 'Montserrat', sans-serif;
```

2020-01-13 08:52 UTC, AleksandraKaminska approved these changes

2020-01-13 08:59 UTC, merged