[SD-704] Corrects carausel arrows on pdp and homepage
spree/spree pull request #9800
Opened 2020-01-15 13:04 UTC by PSzyszkaSpark

Fixes https://spark-solutions.atlassian.net/browse/SD-704

2020-01-16 09:53 UTC, AleksandraKaminska commented on frontend/app/assets/stylesheets/spree/frontend/components-bootstrap/carousel.scss
> +    @media (min-width: 1307px) {
Why such a number?

2020-01-16 09:59 UTC, AleksandraKaminska requested changes

2020-01-16 10:01 UTC, AleksandraKaminska requested changes

2020-01-16 10:01 UTC, AleksandraKaminska commented on frontend/app/views/spree/home/_carousel.html.erb
> +        class="d-flex h-100 position-absolute justify-content-center align-items-center carousel-icon-control carousel-icon-control--previous"
The same. Please revert this line.

2020-01-19 16:32 UTC, damianlegawiec approved these changes

2020-01-19 16:32 UTC, merged