[SD-661] Adds og:image meta property
spree/spree pull request #9809
Opened 2020-01-16 13:56 UTC by PSzyszkaSpark

Fixes https://spark-solutions.atlassian.net/browse/SD-661

2020-01-16 16:29 UTC, damianlegawiec requested changes

2020-01-16 16:29 UTC, damianlegawiec commented on core/app/helpers/spree/base_helper.rb
> +        ActiveStorage::Blob.service.path_for(image.attachment.key)
```suggestion
        main_app.url_for(image.url)
```

2020-01-16 16:29 UTC, damianlegawiec commented on core/app/helpers/spree/base_helper.rb
> +        image_tag(Spree::Config[:logo])[10..image_tag(Spree::Config[:logo]).length - 5]
```suggestion
        main_app.url(Spree::Config[:logo])
```

2020-01-17 10:02 UTC, damianlegawiec requested changes
@PSzyszkaSpark also let's add some tests for this

2020-01-17 10:02 UTC, damianlegawiec commented on core/app/helpers/spree/base_helper.rb
> +      image.nil? ? asset_path(Spree::Config[:logo]) : main_app.url_for(image.url(image))
```suggestion
      image.nil? ? asset_path(Spree::Config[:logo]) : main_app.url_for(image.attachment)
```

2020-01-17 11:37 UTC, damianlegawiec approved these changes

2020-01-17 13:05 UTC, damianlegawiec approved these changes

2020-01-17 13:06 UTC, merged

2020-02-01 16:41 UTC, LemonAndroid commented on core/spec/helpers/base_helper_spec.rb
> +          expect(image_url_path).to eq asset_path(Spree::Config[:logo])
What if the shop is selling Superman and Batman figures and the user googles "Batman" and the shop has a picture of "Superman" as it's `Spree::Config[:logo]`?

Will the user see a picture of "Superman" then if they google "Batman" in google image search?