[SD-663] Corrects breadcrumbs in frontend_helper.rb
spree/spree pull request #9815
Opened 2020-01-20 09:29 UTC by PSzyszkaSpark

Fixes https://spark-solutions.atlassian.net/browse/SD-663

2020-01-29 12:54 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        crumbs << content_tag(:li, content_tag(:span, content_tag(:span, product.name) + separator), class: 'breadcrumb-item', itemid: spree.product_path(product, taxon_id: taxon.try(:id)), position:
@PSzyszkaSpark shouldn't this  be a subsequent number, eg. if we have 2 taxons it would be 3 ?

2020-02-06 11:48 UTC, pmilewski approved these changes

2020-02-07 14:09 UTC, damianlegawiec requested changes

2020-02-07 14:09 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        crumbs << content_tag(:li, content_tag(:span, content_tag(:span, product.name) + separator), class: 'breadcrumb-item', itemid: spree.product_path(product, taxon_id: taxon.try(:id)), position:
```suggestion
        ancestors =  taxon.ancestors.where.not(parent_id: nil)
        crumbs << ancestors.each_with_index.map { |ancestor, index| content_tag(:li, content_tag(:span, link_to(content_tag(:span, ancestor.name, itemprop: 'name'), seo_url(ancestor, params: permitted_product_params), itemprop: 'url') + separator, itemprop: 'item'), itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListElement', itemid: seo_url(ancestor, params: permitted_product_params), class: 'breadcrumb-item', position: index + 1) }
        crumbs << content_tag(:li, content_tag(:span, link_to(content_tag(:span, taxon.name, itemprop: 'name'), seo_url(taxon, params: permitted_product_params), itemprop: 'url') + separator, itemprop: 'item'), class: 'breadcrumb-item', itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListElement', itemid: seo_url(taxon, params: permitted_product_params), position: ancestors.size + 1
        content_tag(:li, content_tag(:span, content_tag(:span, product.name) + separator), class: 'breadcrumb-item', itemid: spree.product_path(product, taxon_id: taxon.try(:id)), position: ancestors.size + 2) if product
```

This way we're reducing number of SQL queries and keeping everything in memory making it more performant

2020-02-07 14:18 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
>          crumbs << content_tag(:li, content_tag(:span, Spree.t(:products), itemprop: 'item'), class: 'active', itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListEleme
```suggestion
        crumbs << content_tag(:li, content_tag(:span, Spree.t(:products), itemprop: 'item'), class: 'active', itemscope: 'itemscope', itemtype: 'https://schema.org/ListItem', itemprop: 'itemListElement', position: 1)
```

2020-02-07 14:18 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> +        ancestors =  taxon.ancestors.where.not(parent_id: nil)
```suggestion
        ancestors = taxon.ancestors.where.not(parent_id: nil)
```

2020-02-10 10:44 UTC, damianlegawiec approved these changes

2020-02-10 10:45 UTC, merged