[SD-786] Clicking on any input zoom in the page
spree/spree pull request #9933
Opened 2020-02-17 09:08 UTC by pmilewski

2020-02-17 09:41 UTC, PSzyszkaSpark approved these changes

2020-02-17 10:23 UTC, AleksandraKaminska commented
Could you use `touch-action: manipulation;` on input fields instead?
"Maximum-scale is designed to prevent the user from zooming too far in on a page, and is not intrinsically bad, however it is relatively easy to accidentally set up the viewport so that the maximum-scale disables using from zooming at all, so it is generally not recommended. For this reason, Apple decided to ignore the declarations of user-scalable, minimum-scale, and maximum-scale, as of iOS 10."

2020-02-17 10:26 UTC, AleksandraKaminska requested changes
Added comment ^

2020-02-18 15:29 UTC, AleksandraKaminska approved these changes

2020-02-18 16:23 UTC, merged