[SD-772] Creates user identification by segment
spree/spree pull request #9937
Opened 2020-02-17 13:03 UTC by PSzyszkaSpark

Fixes https://spark-solutions.atlassian.net/browse/SD-772

2020-02-17 13:07 UTC, przemosk commented on frontend/app/views/spree/shared/_link_to_account.html.erb
> +<% if try_spree_current_user %>
instead of keepping logic in view, maybe you could implement here some helper ? I would suggest also some serializer for analytics data.

2020-02-17 13:11 UTC, damianlegawiec requested changes

2020-02-17 13:11 UTC, damianlegawiec commented on core/app/models/concerns/spree/user_methods.rb
> +      bill_address.first_name
```suggestion
      bill_address&.first_name
```

2020-02-17 13:11 UTC, damianlegawiec commented on core/app/models/concerns/spree/user_methods.rb
> +      bill_address.last_name
```suggestion
      bill_address&.last_name
```

2020-02-17 13:11 UTC, damianlegawiec commented on core/app/models/concerns/spree/user_methods.rb
> +      bill_address.phone
@PSzyszkaSpark let's use delegate for those attributes

2020-02-18 13:29 UTC, przemosk commented on core/app/models/concerns/spree/user_methods.rb
> +    delegate :first_name, to: :first_name
shouldn't be here object name ?

2020-02-18 17:13 UTC, closed without merging