[WIP] Remove unnecessary position attrs
spree/spree pull request #9975
Opened 2020-02-21 15:25 UTC by Punkbooster

2020-02-24 10:32 UTC, PSzyszkaSpark approved these changes

2020-02-25 08:58 UTC, damianlegawiec requested changes

2020-02-25 08:58 UTC, damianlegawiec commented on frontend/app/helpers/spree/frontend_helper.rb
> -    def spree_breadcrumbs(taxon, separator = '', product = nil)
@Punkbooster we need to leave this `separator` param for backward compatibility

2020-02-26 20:12 UTC, damianlegawiec approved these changes

2020-02-26 20:25 UTC, merged