[WIP][SD-806] Adds product preview buttons in product admin panel
spree/spree pull request #9999
Opened 2020-02-25 07:05 UTC by PSzyszkaSpark

Fixes https://spark-solutions.atlassian.net/browse/SD-806

2020-02-25 08:53 UTC, damianlegawiec requested changes
@PSzyszkaSpark let's move 

```
<% if frontend_available? %>
    <%= button_link_to Spree.t(:preview_product), product_url(@product), { class: "btn-outline-secondary", icon: 'eye-open', id: 'admin_preview_product', target: :_blank } %>
  <% end %>
```

into a helper method `product_preview_link(product)` in `Spree::Admin::BaseHelper`

2020-02-25 08:53 UTC, damianlegawiec commented on backend/app/views/spree/admin/images/index.html.erb
> +    <%= button_link_to Spree.t(:preview_product), product_url(@product), { class: "btn-outline-secondary", icon: 'eye-open', id: 'admin_preview_product', target: :_blank } %>
```suggestion
    <%= button_link_to Spree.t(:preview_product), product_url(@product), { class: "btn-outline-secondary", icon: 'eye-open', id: 'admin_preview_product', target: :blank } %>
```

2020-02-25 09:39 UTC, damianlegawiec commented on backend/app/helpers/spree/admin/base_helper.rb
> +      def product_preview_link(product)
```suggestion
      def product_preview_link(product)
         return unless frontend_available?
         
```

2020-02-25 09:39 UTC, damianlegawiec commented on backend/app/helpers/spree/admin/base_helper.rb
> +            spree.product_url(@product),
```suggestion
            spree.product_url(product),
```

2020-03-11 14:01 UTC, pmilewski approved these changes

2020-03-11 16:36 UTC, damianlegawiec approved these changes

2020-03-11 16:36 UTC, merged